# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.list_oauth_apps_response import ListOauthAppsResponse
from ..types.oauth_app import OauthApp
from .raw_client import AsyncRawOauthAppsClient, RawOauthAppsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OauthAppsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOauthAppsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOauthAppsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOauthAppsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        app: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[OauthApp, ListOauthAppsResponse]:
        """
        List the custom OAuth clients available to the project, including the parent workspace's

        Parameters
        ----------
        after : typing.Optional[str]
            The cursor to start from for pagination

        before : typing.Optional[str]
            The cursor to end before for pagination

        limit : typing.Optional[int]
            The maximum number of results to return

        app : typing.Optional[str]
            Only return OAuth clients for this app (ID or name slug)

        q : typing.Optional[str]
            A search query to filter the OAuth clients by name or description

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[OauthApp, ListOauthAppsResponse]
            OAuth clients listed

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        response = client.oauth_apps.list(
            after="after",
            before="before",
            limit=1,
            app="app",
            q="q",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            after=after, before=before, limit=limit, app=app, q=q, request_options=request_options
        )

    def create(
        self,
        *,
        app: str,
        client_id: str,
        client_secret: str,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        additional_scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OauthApp:
        """
        Register a custom OAuth client for an app

        Parameters
        ----------
        app : str
            The app's ID or name slug. The app must have custom OAuth clients enabled.

        client_id : str
            The OAuth client ID registered with the upstream provider

        client_secret : str
            The OAuth client secret. Write-only; never returned in responses.

        name : typing.Optional[str]
            Display name of the OAuth client

        description : typing.Optional[str]
            Description of the OAuth client

        scopes : typing.Optional[typing.Sequence[str]]
            OAuth scopes to request when users connect through this client

        additional_scopes : typing.Optional[typing.Sequence[str]]
            Extra OAuth scopes users may grant on top of the base scopes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthApp
            OAuth client created

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.oauth_apps.create(
            app="app",
            client_id="client_id",
            client_secret="client_secret",
        )
        """
        _response = self._raw_client.create(
            app=app,
            client_id=client_id,
            client_secret=client_secret,
            name=name,
            description=description,
            scopes=scopes,
            additional_scopes=additional_scopes,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> OauthApp:
        """
        Get the configuration of a specific custom OAuth client

        Parameters
        ----------
        id : str
            The OAuth client ID, which starts with `oa_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthApp
            OAuth client retrieved

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.oauth_apps.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        client_secret: typing.Optional[str] = OMIT,
        scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        additional_scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OauthApp:
        """
        Update a custom OAuth client's credentials or configuration

        Parameters
        ----------
        id : str
            The OAuth client ID, which starts with `oa_`.

        name : typing.Optional[str]
            Display name of the OAuth client

        description : typing.Optional[str]
            Description of the OAuth client

        client_id : typing.Optional[str]
            The OAuth client ID registered with the upstream provider

        client_secret : typing.Optional[str]
            The OAuth client secret. Write-only; blank values are ignored and the existing secret is kept.

        scopes : typing.Optional[typing.Sequence[str]]
            OAuth scopes to request when users connect through this client

        additional_scopes : typing.Optional[typing.Sequence[str]]
            Extra OAuth scopes users may grant on top of the base scopes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthApp
            OAuth client updated

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.oauth_apps.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            description=description,
            client_id=client_id,
            client_secret=client_secret,
            scopes=scopes,
            additional_scopes=additional_scopes,
            request_options=request_options,
        )
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a custom OAuth client that is no longer in use

        Parameters
        ----------
        id : str
            The OAuth client ID, which starts with `oa_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.oauth_apps.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data


class AsyncOauthAppsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOauthAppsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOauthAppsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOauthAppsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        app: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[OauthApp, ListOauthAppsResponse]:
        """
        List the custom OAuth clients available to the project, including the parent workspace's

        Parameters
        ----------
        after : typing.Optional[str]
            The cursor to start from for pagination

        before : typing.Optional[str]
            The cursor to end before for pagination

        limit : typing.Optional[int]
            The maximum number of results to return

        app : typing.Optional[str]
            Only return OAuth clients for this app (ID or name slug)

        q : typing.Optional[str]
            A search query to filter the OAuth clients by name or description

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[OauthApp, ListOauthAppsResponse]
            OAuth clients listed

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            response = await client.oauth_apps.list(
                after="after",
                before="before",
                limit=1,
                app="app",
                q="q",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            after=after, before=before, limit=limit, app=app, q=q, request_options=request_options
        )

    async def create(
        self,
        *,
        app: str,
        client_id: str,
        client_secret: str,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        additional_scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OauthApp:
        """
        Register a custom OAuth client for an app

        Parameters
        ----------
        app : str
            The app's ID or name slug. The app must have custom OAuth clients enabled.

        client_id : str
            The OAuth client ID registered with the upstream provider

        client_secret : str
            The OAuth client secret. Write-only; never returned in responses.

        name : typing.Optional[str]
            Display name of the OAuth client

        description : typing.Optional[str]
            Description of the OAuth client

        scopes : typing.Optional[typing.Sequence[str]]
            OAuth scopes to request when users connect through this client

        additional_scopes : typing.Optional[typing.Sequence[str]]
            Extra OAuth scopes users may grant on top of the base scopes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthApp
            OAuth client created

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.oauth_apps.create(
                app="app",
                client_id="client_id",
                client_secret="client_secret",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            app=app,
            client_id=client_id,
            client_secret=client_secret,
            name=name,
            description=description,
            scopes=scopes,
            additional_scopes=additional_scopes,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> OauthApp:
        """
        Get the configuration of a specific custom OAuth client

        Parameters
        ----------
        id : str
            The OAuth client ID, which starts with `oa_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthApp
            OAuth client retrieved

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.oauth_apps.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        client_id: typing.Optional[str] = OMIT,
        client_secret: typing.Optional[str] = OMIT,
        scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        additional_scopes: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OauthApp:
        """
        Update a custom OAuth client's credentials or configuration

        Parameters
        ----------
        id : str
            The OAuth client ID, which starts with `oa_`.

        name : typing.Optional[str]
            Display name of the OAuth client

        description : typing.Optional[str]
            Description of the OAuth client

        client_id : typing.Optional[str]
            The OAuth client ID registered with the upstream provider

        client_secret : typing.Optional[str]
            The OAuth client secret. Write-only; blank values are ignored and the existing secret is kept.

        scopes : typing.Optional[typing.Sequence[str]]
            OAuth scopes to request when users connect through this client

        additional_scopes : typing.Optional[typing.Sequence[str]]
            Extra OAuth scopes users may grant on top of the base scopes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthApp
            OAuth client updated

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.oauth_apps.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            description=description,
            client_id=client_id,
            client_secret=client_secret,
            scopes=scopes,
            additional_scopes=additional_scopes,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a custom OAuth client that is no longer in use

        Parameters
        ----------
        id : str
            The OAuth client ID, which starts with `oa_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.oauth_apps.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data
