# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.stash_id import StashId

RunActionOptsStashId = typing.Union[typing.Optional[StashId], typing.Literal["NEW"], bool]
