# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.too_many_requests_error import TooManyRequestsError
from ..types.proxy_response import ProxyResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawProxyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated GET request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="GET",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        _response.read()
                        if not _response.text.strip():
                            return HttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return HttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                _response.read()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def post(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated POST request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="POST",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        _response.read()
                        if not _response.text.strip():
                            return HttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return HttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                _response.read()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def put(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated PUT request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PUT",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        _response.read()
                        if not _response.text.strip():
                            return HttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return HttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                _response.read()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated DELETE request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="DELETE",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        _response.read()
                        if not _response.text.strip():
                            return HttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return HttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                _response.read()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def patch(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated PATCH request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PATCH",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        _response.read()
                        if not _response.text.strip():
                            return HttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return HttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                _response.read()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawProxyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated GET request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="GET",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        await _response.aread()
                        if not _response.text.strip():
                            return AsyncHttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return AsyncHttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                await _response.aread()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def post(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated POST request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="POST",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        await _response.aread()
                        if not _response.text.strip():
                            return AsyncHttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return AsyncHttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                await _response.aread()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def put(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated PUT request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PUT",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        await _response.aread()
                        if not _response.text.strip():
                            return AsyncHttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return AsyncHttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                await _response.aread()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated DELETE request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="DELETE",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        await _response.aread()
                        if not _response.text.strip():
                            return AsyncHttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return AsyncHttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                await _response.aread()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def patch(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated PATCH request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PATCH",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:
            try:
                if 200 <= _response.status_code < 300:
                    # Check Content-Type to determine how to handle the response
                    content_type = _response.headers.get("content-type", "").lower()
                    is_json = "application/json" in content_type or not content_type

                    if is_json:
                        # Parse as JSON
                        await _response.aread()
                        if not _response.text.strip():
                            return AsyncHttpResponse(response=_response, data=None)
                        _data = typing.cast(
                            ProxyResponse,
                            parse_obj_as(
                                type_=ProxyResponse,  # type: ignore
                                object_=_response.json(),
                            ),
                        )
                        return AsyncHttpResponse(response=_response, data=_data)
                    else:
                        # Stream binary content
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                await _response.aread()
                if _response.status_code == 429:
                    raise TooManyRequestsError(
                        headers=dict(_response.headers),
                        body=typing.cast(
                            typing.Optional[typing.Any],
                            parse_obj_as(
                                type_=typing.Optional[typing.Any],  # type: ignore
                                object_=_response.json(),
                            ),
                        ),
                    )
                _response_json = _response.json()
            except JSONDecodeError:
                raise ApiError(
                    status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                )
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
