# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.too_many_requests_error import TooManyRequestsError
from ..types.proxy_response import ProxyResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


def _create_stream_iterator(stream_context, response, chunk_size=None):
    """Create an iterator that ensures proper cleanup after streaming."""
    try:
        for chunk in response.iter_bytes(chunk_size=chunk_size):
            yield chunk
    finally:
        stream_context.__exit__(None, None, None)


async def _create_async_stream_iterator(stream_context, response, chunk_size=None):
    """Create an async iterator that ensures proper cleanup after streaming."""
    try:
        async for chunk in response.aiter_bytes(chunk_size=chunk_size):
            yield chunk
    finally:
        await stream_context.__aexit__(None, None, None)


class RawProxyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated GET request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="GET",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        )
        _stream_context = _response.__enter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    _stream_context.read()
                    _response.__exit__(None, None, None)
                    if not _stream_context.text.strip():
                        return HttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return HttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return HttpResponse(response=_stream_context, data=_create_stream_iterator(_response, _stream_context, _chunk_size))
            _stream_context.read()
            _response.__exit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            _response.__exit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            _response.__exit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    def post(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated POST request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="POST",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        _stream_context = _response.__enter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    _stream_context.read()
                    _response.__exit__(None, None, None)
                    if not _stream_context.text.strip():
                        return HttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return HttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return HttpResponse(response=_stream_context, data=_create_stream_iterator(_response, _stream_context, _chunk_size))
            _stream_context.read()
            _response.__exit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            _response.__exit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            _response.__exit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    def put(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated PUT request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PUT",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        _stream_context = _response.__enter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    _stream_context.read()
                    _response.__exit__(None, None, None)
                    if not _stream_context.text.strip():
                        return HttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return HttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return HttpResponse(response=_stream_context, data=_create_stream_iterator(_response, _stream_context, _chunk_size))
            _stream_context.read()
            _response.__exit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            _response.__exit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            _response.__exit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    def delete(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated DELETE request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="DELETE",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        )
        _stream_context = _response.__enter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    _stream_context.read()
                    _response.__exit__(None, None, None)
                    if not _stream_context.text.strip():
                        return HttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return HttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return HttpResponse(response=_stream_context, data=_create_stream_iterator(_response, _stream_context, _chunk_size))
            _stream_context.read()
            _response.__exit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            _response.__exit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            _response.__exit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    def patch(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]:
        """
        Forward an authenticated PATCH request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        HttpResponse[typing.Union[ProxyResponse, typing.Iterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PATCH",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        _stream_context = _response.__enter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    _stream_context.read()
                    _response.__exit__(None, None, None)
                    if not _stream_context.text.strip():
                        return HttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return HttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return HttpResponse(response=_stream_context, data=_create_stream_iterator(_response, _stream_context, _chunk_size))
            _stream_context.read()
            _response.__exit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            _response.__exit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            _response.__exit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)


class AsyncRawProxyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated GET request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="GET",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        )
        _stream_context = await _response.__aenter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    await _stream_context.aread()
                    await _response.__aexit__(None, None, None)
                    if not _stream_context.text.strip():
                        return AsyncHttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return AsyncHttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return AsyncHttpResponse(response=_stream_context, data=_create_async_stream_iterator(_response, _stream_context, _chunk_size))
            await _stream_context.aread()
            await _response.__aexit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            await _response.__aexit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            await _response.__aexit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    async def post(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated POST request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="POST",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        _stream_context = await _response.__aenter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    await _stream_context.aread()
                    await _response.__aexit__(None, None, None)
                    if not _stream_context.text.strip():
                        return AsyncHttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return AsyncHttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return AsyncHttpResponse(response=_stream_context, data=_create_async_stream_iterator(_response, _stream_context, _chunk_size))
            await _stream_context.aread()
            await _response.__aexit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            await _response.__aexit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            await _response.__aexit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    async def put(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated PUT request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PUT",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        _stream_context = await _response.__aenter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    await _stream_context.aread()
                    await _response.__aexit__(None, None, None)
                    if not _stream_context.text.strip():
                        return AsyncHttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return AsyncHttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return AsyncHttpResponse(response=_stream_context, data=_create_async_stream_iterator(_response, _stream_context, _chunk_size))
            await _stream_context.aread()
            await _response.__aexit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            await _response.__aexit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            await _response.__aexit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    async def delete(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated DELETE request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="DELETE",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            request_options=request_options,
        )
        _stream_context = await _response.__aenter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    await _stream_context.aread()
                    await _response.__aexit__(None, None, None)
                    if not _stream_context.text.strip():
                        return AsyncHttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return AsyncHttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return AsyncHttpResponse(response=_stream_context, data=_create_async_stream_iterator(_response, _stream_context, _chunk_size))
            await _stream_context.aread()
            await _response.__aexit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            await _response.__aexit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            await _response.__aexit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)

    async def patch(
        self,
        url_64: str,
        *,
        external_user_id: str,
        account_id: str,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]:
        """
        Forward an authenticated PATCH request to an external API using an external user's account credentials

        Parameters
        ----------
        url_64 : str
            Base64-encoded target URL

        external_user_id : str
            The external user ID for the proxy request

        account_id : str
            The account ID to use for authentication

        request : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        AsyncHttpResponse[typing.Union[ProxyResponse, typing.AsyncIterator[bytes]]]
            proxy request successful
        """
        _response = self._client_wrapper.httpx_client.stream(
            f"v1/connect/{jsonable_encoder(self._client_wrapper._project_id)}/proxy/{jsonable_encoder(url_64)}",
            method="PATCH",
            params={
                "external_user_id": external_user_id,
                "account_id": account_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        _stream_context = await _response.__aenter__()

        try:
            if 200 <= _stream_context.status_code < 300:
                # Check Content-Type to determine how to handle the response
                content_type = _stream_context.headers.get("content-type", "").lower()
                is_json = "application/json" in content_type or not content_type

                if is_json:
                    # Parse as JSON and close the stream
                    await _stream_context.aread()
                    await _response.__aexit__(None, None, None)
                    if not _stream_context.text.strip():
                        return AsyncHttpResponse(response=_stream_context, data=None)
                    _data = typing.cast(
                        ProxyResponse,
                        parse_obj_as(
                            type_=ProxyResponse,  # type: ignore
                            object_=_stream_context.json(),
                        ),
                    )
                    return AsyncHttpResponse(response=_stream_context, data=_data)
                else:
                    # Stream binary content - keep stream open for lazy iteration
                    _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                    return AsyncHttpResponse(response=_stream_context, data=_create_async_stream_iterator(_response, _stream_context, _chunk_size))
            await _stream_context.aread()
            await _response.__aexit__(None, None, None)
            _error_content_type = _stream_context.headers.get("content-type", "").lower()
            if _stream_context.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_stream_context.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_stream_context.json() if "application/json" in _error_content_type else _stream_context.text,
                        ),
                    ),
                )
            if "application/json" in _error_content_type:
                _response_body = _stream_context.json()
            else:
                _response_body = _stream_context.text
        except JSONDecodeError:
            await _response.__aexit__(None, None, None)
            raise ApiError(
                status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_stream_context.text
            )
        except Exception:
            await _response.__aexit__(None, None, None)
            raise
        raise ApiError(status_code=_stream_context.status_code, headers=dict(_stream_context.headers), body=_response_body)
