# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.app_override import AppOverride
from ..types.list_app_overrides_response import ListAppOverridesResponse
from .raw_client import AsyncRawAppOverridesClient, RawAppOverridesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AppOverridesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAppOverridesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAppOverridesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAppOverridesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        app: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[AppOverride, ListAppOverridesResponse]:
        """
        List the app overrides available to the project, including the parent workspace's

        Parameters
        ----------
        after : typing.Optional[str]
            The cursor to start from for pagination

        before : typing.Optional[str]
            The cursor to end before for pagination

        limit : typing.Optional[int]
            The maximum number of results to return

        app : typing.Optional[str]
            Only return overrides for this app (ID or name slug)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[AppOverride, ListAppOverridesResponse]
            app overrides listed

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        response = client.app_overrides.list(
            after="after",
            before="before",
            limit=1,
            app="app",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(after=after, before=before, limit=limit, app=app, request_options=request_options)

    def create(
        self,
        *,
        app: str,
        name: str,
        oauth_app_id: typing.Optional[str] = OMIT,
        cfmap: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AppOverride:
        """
        Create an app override with pre-defined custom field values

        Parameters
        ----------
        app : str
            The app's ID or name slug

        name : str
            Name of the override, unique per owner

        oauth_app_id : typing.Optional[str]
            Hash ID of the custom OAuth client to use

        cfmap : typing.Optional[typing.Dict[str, typing.Any]]
            Pre-defined custom field values, keyed by the app's custom field names. Sensitive (password-type) fields are rejected.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AppOverride
            app override created

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.app_overrides.create(
            app="app",
            name="name",
        )
        """
        _response = self._raw_client.create(
            app=app, name=name, oauth_app_id=oauth_app_id, cfmap=cfmap, request_options=request_options
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AppOverride:
        """
        Get the configuration of a specific app override

        Parameters
        ----------
        id : str
            The app override ID, which starts with `ao_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AppOverride
            app override retrieved

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.app_overrides.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        oauth_app_id: typing.Optional[str] = OMIT,
        cfmap: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AppOverride:
        """
        Update an app override's name, custom field values, or OAuth client selection

        Parameters
        ----------
        id : str
            The app override ID, which starts with `ao_`.

        name : typing.Optional[str]
            Name of the override, unique per owner

        oauth_app_id : typing.Optional[str]
            Hash ID of the custom OAuth client to use. Pass null to clear it.

        cfmap : typing.Optional[typing.Dict[str, typing.Any]]
            Pre-defined custom field values, keyed by the app's custom field names. Sensitive (password-type) fields are rejected.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AppOverride
            app override updated

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.app_overrides.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id, name=name, oauth_app_id=oauth_app_id, cfmap=cfmap, request_options=request_options
        )
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete an app override without affecting accounts already connected with it

        Parameters
        ----------
        id : str
            The app override ID, which starts with `ao_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.app_overrides.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data


class AsyncAppOverridesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAppOverridesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAppOverridesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAppOverridesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        app: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[AppOverride, ListAppOverridesResponse]:
        """
        List the app overrides available to the project, including the parent workspace's

        Parameters
        ----------
        after : typing.Optional[str]
            The cursor to start from for pagination

        before : typing.Optional[str]
            The cursor to end before for pagination

        limit : typing.Optional[int]
            The maximum number of results to return

        app : typing.Optional[str]
            Only return overrides for this app (ID or name slug)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[AppOverride, ListAppOverridesResponse]
            app overrides listed

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            response = await client.app_overrides.list(
                after="after",
                before="before",
                limit=1,
                app="app",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            after=after, before=before, limit=limit, app=app, request_options=request_options
        )

    async def create(
        self,
        *,
        app: str,
        name: str,
        oauth_app_id: typing.Optional[str] = OMIT,
        cfmap: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AppOverride:
        """
        Create an app override with pre-defined custom field values

        Parameters
        ----------
        app : str
            The app's ID or name slug

        name : str
            Name of the override, unique per owner

        oauth_app_id : typing.Optional[str]
            Hash ID of the custom OAuth client to use

        cfmap : typing.Optional[typing.Dict[str, typing.Any]]
            Pre-defined custom field values, keyed by the app's custom field names. Sensitive (password-type) fields are rejected.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AppOverride
            app override created

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.app_overrides.create(
                app="app",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            app=app, name=name, oauth_app_id=oauth_app_id, cfmap=cfmap, request_options=request_options
        )
        return _response.data

    async def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AppOverride:
        """
        Get the configuration of a specific app override

        Parameters
        ----------
        id : str
            The app override ID, which starts with `ao_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AppOverride
            app override retrieved

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.app_overrides.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        oauth_app_id: typing.Optional[str] = OMIT,
        cfmap: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AppOverride:
        """
        Update an app override's name, custom field values, or OAuth client selection

        Parameters
        ----------
        id : str
            The app override ID, which starts with `ao_`.

        name : typing.Optional[str]
            Name of the override, unique per owner

        oauth_app_id : typing.Optional[str]
            Hash ID of the custom OAuth client to use. Pass null to clear it.

        cfmap : typing.Optional[typing.Dict[str, typing.Any]]
            Pre-defined custom field values, keyed by the app's custom field names. Sensitive (password-type) fields are rejected.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AppOverride
            app override updated

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.app_overrides.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id, name=name, oauth_app_id=oauth_app_id, cfmap=cfmap, request_options=request_options
        )
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete an app override without affecting accounts already connected with it

        Parameters
        ----------
        id : str
            The app override ID, which starts with `ao_`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.app_overrides.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data
