# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.get_webhook_response import GetWebhookResponse
from ..types.get_webhook_with_signing_key_response import GetWebhookWithSigningKeyResponse
from ..types.set_webhook_response import SetWebhookResponse
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def retrieve(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetWebhookResponse:
        """
        Retrieve the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookResponse
            webhook retrieved

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.webhooks.retrieve()
        """
        _response = self._raw_client.retrieve(request_options=request_options)
        return _response.data

    def update(self, *, url: str, request_options: typing.Optional[RequestOptions] = None) -> SetWebhookResponse:
        """
        Create or update the webhook URL for a project environment. Creating a webhook returns `signing_key`; updating an existing webhook does not.

        Parameters
        ----------
        url : str
            The webhook URL to set

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetWebhookResponse
            webhook updated

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.webhooks.update(
            url="url",
        )
        """
        _response = self._raw_client.update(url=url, request_options=request_options)
        return _response.data

    def delete(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.webhooks.delete()
        """
        _response = self._raw_client.delete(request_options=request_options)
        return _response.data

    def regenerate_webhook_signing_key(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhookWithSigningKeyResponse:
        """
        Regenerate the signing key for the project environment webhook

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookWithSigningKeyResponse
            signing key regenerated

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.webhooks.regenerate_webhook_signing_key()
        """
        _response = self._raw_client.regenerate_webhook_signing_key(request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def retrieve(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetWebhookResponse:
        """
        Retrieve the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookResponse
            webhook retrieved

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.webhooks.retrieve()


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(request_options=request_options)
        return _response.data

    async def update(self, *, url: str, request_options: typing.Optional[RequestOptions] = None) -> SetWebhookResponse:
        """
        Create or update the webhook URL for a project environment. Creating a webhook returns `signing_key`; updating an existing webhook does not.

        Parameters
        ----------
        url : str
            The webhook URL to set

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetWebhookResponse
            webhook updated

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.webhooks.update(
                url="url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(url=url, request_options=request_options)
        return _response.data

    async def delete(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.webhooks.delete()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(request_options=request_options)
        return _response.data

    async def regenerate_webhook_signing_key(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhookWithSigningKeyResponse:
        """
        Regenerate the signing key for the project environment webhook

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookWithSigningKeyResponse
            signing key regenerated

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.webhooks.regenerate_webhook_signing_key()


        asyncio.run(main())
        """
        _response = await self._raw_client.regenerate_webhook_signing_key(request_options=request_options)
        return _response.data
