# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AccountCredentials(UniversalBaseModel):
    """
    The credentials associated with the account, if the `include_credentials` parameter was set to true in the request (only applicable for BYOA apps). In addition to the well-known OAuth fields listed below, this object may contain app-specific custom fields (e.g. `base_url`).
    """

    oauth_client_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The OAuth client ID for the app, if applicable
    """

    oauth_access_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The OAuth access token
    """

    oauth_refresh_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The OAuth refresh token
    """

    oauth_uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique OAuth user identifier
    """

    oauth_signer_uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The OAuth signer URI, if the app uses a custom OAuth signer
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
