# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .app import App


class AppOverride(UniversalBaseModel):
    """
    A named set of pre-defined custom field values for an app, owned by the workspace or a project. For OAuth apps it can select the custom OAuth client to use.
    """

    id: str = pydantic.Field()
    """
    Hash ID for the app override
    """

    name: str = pydantic.Field()
    """
    Name of the override, unique per owner
    """

    app: App
    oauth_app_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hash ID of the custom OAuth client the override selects, if any
    """

    cfmap: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Pre-defined custom field values, keyed by the app's custom field names. Sensitive (password-type) fields cannot be pre-defined.
    """

    owner_id: str = pydantic.Field()
    """
    Hash ID of the owner: the workspace (o_...) or the project (proj_...)
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
