# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .app_scope_profiles_item_name import AppScopeProfilesItemName


class AppScopeProfilesItem(UniversalBaseModel):
    name: AppScopeProfilesItemName = pydantic.Field()
    """
    The profile name. Pass this back as `oauth_scope_profile` when starting the OAuth flow for this app.
    """

    scopes: typing.List[str] = pydantic.Field()
    """
    The actual OAuth scopes of the upstream API that the user will be asked to authorize when this profile is selected.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
