# This file was auto-generated by Fern from our API Definition.

import typing

from .configure_prop_option_item import ConfigurePropOptionItem

ConfigurePropOption = typing.Optional[typing.List[ConfigurePropOptionItem]]
