# This file was auto-generated by Fern from our API Definition.

import typing

ConfigurablePropType = typing.Union[
    typing.Literal[
        "app",
        "$.interface.apphook",
        "$.interface.http",
        "$.interface.timer",
        "data_store",
        "$.service.db",
        "boolean",
        "integer",
        "object",
        "any",
        "string",
        "$.airtable.baseId",
        "$.airtable.tableId",
        "$.airtable.viewId",
        "$.airtable.fieldId",
        "$.discord.channel",
        "http_request",
        "sql",
        "alert",
        "dir",
    ],
    typing.Any,
]
