# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ConfiguredPropSql(UniversalBaseModel):
    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    The raw SQL query, as provided by the user
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The SQL query to execute
    """

    params: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The list of parameters for the prepared statement
    """

    use_prepared_statements: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="usePreparedStatements")
    ] = pydantic.Field(default=None)
    """
    Whether to use prepared statements for the query or not
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
