# This file was auto-generated by Fern from our API Definition.

import typing

from .configurable_prop_airtable_base_id import ConfigurablePropAirtableBaseId
from .configurable_prop_airtable_field_id import ConfigurablePropAirtableFieldId
from .configurable_prop_airtable_table_id import ConfigurablePropAirtableTableId
from .configurable_prop_airtable_view_id import ConfigurablePropAirtableViewId
from .configurable_prop_alert import ConfigurablePropAlert
from .configurable_prop_any import ConfigurablePropAny
from .configurable_prop_app import ConfigurablePropApp
from .configurable_prop_apphook import ConfigurablePropApphook
from .configurable_prop_boolean import ConfigurablePropBoolean
from .configurable_prop_data_store import ConfigurablePropDataStore
from .configurable_prop_db import ConfigurablePropDb
from .configurable_prop_dir import ConfigurablePropDir
from .configurable_prop_discord_channel import ConfigurablePropDiscordChannel
from .configurable_prop_discord_channel_array import ConfigurablePropDiscordChannelArray
from .configurable_prop_http import ConfigurablePropHttp
from .configurable_prop_http_request import ConfigurablePropHttpRequest
from .configurable_prop_integer import ConfigurablePropInteger
from .configurable_prop_integer_array import ConfigurablePropIntegerArray
from .configurable_prop_object import ConfigurablePropObject
from .configurable_prop_sql import ConfigurablePropSql
from .configurable_prop_string import ConfigurablePropString
from .configurable_prop_string_array import ConfigurablePropStringArray
from .configurable_prop_timer import ConfigurablePropTimer

ConfigurableProp = typing.Union[
    ConfigurablePropAlert,
    ConfigurablePropAny,
    ConfigurablePropApp,
    ConfigurablePropBoolean,
    ConfigurablePropDataStore,
    ConfigurablePropDir,
    ConfigurablePropTimer,
    ConfigurablePropApphook,
    ConfigurablePropIntegerArray,
    ConfigurablePropHttp,
    ConfigurablePropHttpRequest,
    ConfigurablePropDb,
    ConfigurablePropSql,
    ConfigurablePropAirtableBaseId,
    ConfigurablePropAirtableTableId,
    ConfigurablePropAirtableViewId,
    ConfigurablePropAirtableFieldId,
    ConfigurablePropDiscordChannel,
    ConfigurablePropDiscordChannelArray,
    ConfigurablePropInteger,
    ConfigurablePropObject,
    ConfigurablePropString,
    ConfigurablePropStringArray,
]
