# This file was auto-generated by Fern from our API Definition.

import typing

from .configured_prop_app import ConfiguredPropApp
from .configured_prop_sql import ConfiguredPropSql

ConfiguredPropValue = typing.Union[
    typing.Optional[typing.Any],
    ConfiguredPropApp,
    ConfiguredPropSql,
    bool,
    float,
    typing.Dict[str, typing.Optional[typing.Any]],
    str,
    typing.List[str],
]
