# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ConnectUsage(UniversalBaseModel):
    """
    Connect usage record
    """

    credits_used: int = pydantic.Field()
    """
    Total Connect credits used
    """

    action_run_credits_used: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits used when running Connect actions
    """

    proxy_credits_used: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits used by Connect proxy requests
    """

    source_emit_credits_used: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits used by Connect source event emissions
    """

    usage_start_ts: int = pydantic.Field()
    """
    Usage window start timestamp (seconds)
    """

    usage_end_ts: int = pydantic.Field()
    """
    Usage window end timestamp (seconds)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
