# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .app_auth_type import AppAuthType
from .app_scope_profiles_item import AppScopeProfilesItem


class OauthApp(UniversalBaseModel):
    """
    A custom OAuth client (bring your own app), presented as its app's metadata merged with the client's own fields. `name` and `description` fall back to the app's when the client doesn't set them. The client secret is write-only and never returned.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hash ID for the OAuth client
    """

    client_id: str = pydantic.Field()
    """
    The OAuth client ID registered with the upstream provider
    """

    scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    OAuth scopes requested when users connect through this client
    """

    additional_scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Extra OAuth scopes users may grant on top of the base scopes
    """

    redirect_uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The redirect URI to register with the upstream OAuth provider
    """

    owner_id: str = pydantic.Field()
    """
    Hash ID of the owner: the workspace (o_...) or the project (proj_...)
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    name_slug: str = pydantic.Field()
    """
    The name slug of the target app (see https://pipedream.com/docs/connect/quickstart#find-your-apps-name-slug)
    """

    name: str = pydantic.Field()
    """
    The human-readable name of the app
    """

    auth_type: typing.Optional[AppAuthType] = None
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A short description of the app
    """

    img_src: str = pydantic.Field()
    """
    The URL to the app's logo
    """

    custom_fields_json: typing.Optional[str] = pydantic.Field(default=None)
    """
    A JSON string representing the custom fields for the app
    """

    categories: typing.List[str] = pydantic.Field()
    """
    Categories associated with the app
    """

    featured_weight: float = pydantic.Field()
    """
    A rough directional ordering of app popularity, subject to changes by Pipedream
    """

    scope_profiles: typing.List[AppScopeProfilesItem] = pydantic.Field()
    """
    Named subsets of the app's OAuth scopes that may be requested when users connect their accounts (via the `oauth_scope_profile` parameter). Empty for apps that don't define any.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
