# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Project(UniversalBaseModel):
    """
    Project that can be accessed via the Connect API
    """

    id: str = pydantic.Field()
    """
    Hash ID for the project
    """

    name: str = pydantic.Field()
    """
    Display name of the project
    """

    app_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    App name shown to Connect users
    """

    support_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Support email configured for the project
    """

    external_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    External URL for the project, if configured
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
