# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TriggerWebhook(UniversalBaseModel):
    """
    A trigger webhook object. `signing_key` is only returned for OAuth-authenticated requests.
    """

    id: str = pydantic.Field()
    """
    The unique ID of the webhook
    """

    url: str = pydantic.Field()
    """
    The webhook URL
    """

    signing_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    The webhook signing key, returned only for OAuth-authenticated requests
    """

    signing_key_set: bool = pydantic.Field()
    """
    Whether a signing key has been set for this webhook
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
