# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .trigger_webhook import TriggerWebhook


class UpdateTriggerWebhooksResponse(UniversalBaseModel):
    """
    Response received when updating trigger webhooks
    """

    webhook_urls: typing.List[str]
    webhooks: typing.List[TriggerWebhook] = pydantic.Field()
    """
    Webhook objects for the configured URLs. `signing_key` is only returned for OAuth-authenticated requests.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
