# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_delivery_state_state import WebhookDeliveryStateState


class WebhookDeliveryState(UniversalBaseModel):
    """
    Current outbound delivery lifecycle and bounded diagnostic evidence
    """

    state: WebhookDeliveryStateState
    since: typing.Optional[int] = pydantic.Field(default=None)
    """
    Time the current state began, in epoch seconds
    """

    last_error: typing.Optional[str] = None
    consecutive_failures: int
    sheds: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
