# This file was auto-generated by Fern from our API Definition.

import typing

WebhookDeliveryStateState = typing.Union[typing.Literal["happy", "penalty", "life_support", "deactivated"], typing.Any]
