# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookWithOptionalSigningKey(UniversalBaseModel):
    """
    A webhook object that may include the signing key. The signing key is returned when a webhook is created, but omitted when an existing webhook is updated.
    """

    id: str = pydantic.Field()
    """
    The unique ID of the webhook
    """

    url: str = pydantic.Field()
    """
    The webhook URL
    """

    signing_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    The webhook signing key, when returned by the endpoint
    """

    signing_key_set: bool = pydantic.Field()
    """
    Whether a signing key has been set for this webhook
    """

    created_at: int = pydantic.Field()
    """
    The time the webhook was created, in epoch seconds
    """

    updated_at: int = pydantic.Field()
    """
    The time the webhook was last updated, in epoch seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
