# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_delivery_state import WebhookDeliveryState
from .webhook_with_signing_key_delivery_backend import WebhookWithSigningKeyDeliveryBackend


class WebhookWithSigningKey(UniversalBaseModel):
    """
    A webhook object including the signing key
    """

    id: str = pydantic.Field()
    """
    The unique ID of the webhook
    """

    url: str = pydantic.Field()
    """
    The webhook URL
    """

    signing_key: str = pydantic.Field()
    """
    The webhook signing key
    """

    signing_key_set: bool = pydantic.Field()
    """
    Whether a signing key has been set for this webhook
    """

    active: typing.Optional[bool] = None
    delivery_backend: typing.Optional[WebhookWithSigningKeyDeliveryBackend] = None
    delivery_state: typing.Optional[WebhookDeliveryState] = None
    created_at: int = pydantic.Field()
    """
    The time the webhook was created, in epoch seconds
    """

    updated_at: int = pydantic.Field()
    """
    The time the webhook was last updated, in epoch seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
