# This file was auto-generated by Fern from our API Definition.

import os
import typing

import httpx
from .client import AsyncClient, Client
from .core.logging import LogConfig, Logger
from .environment import PipedreamEnvironment
from .types.project_environment import ProjectEnvironment


class Pipedream(Client):
    @typing.overload
    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PipedreamEnvironment = PipedreamEnvironment.PROD,
        project_id: str,
        project_environment: typing.Optional[ProjectEnvironment] = os.getenv("PIPEDREAM_PROJECT_ENVIRONMENT"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        client_id: typing.Optional[str] = os.getenv("PIPEDREAM_CLIENT_ID"),
        client_secret: typing.Optional[str] = os.getenv("PIPEDREAM_CLIENT_SECRET"),
    ): ...
    @typing.overload
    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PipedreamEnvironment = PipedreamEnvironment.PROD,
        project_id: str,
        project_environment: typing.Optional[ProjectEnvironment] = os.getenv("PIPEDREAM_PROJECT_ENVIRONMENT"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        token: typing.Callable[[], str],
    ): ...
    def __init__(self, **kwargs: typing.Any):
        super().__init__(**kwargs)


class AsyncPipedream(AsyncClient):
    @typing.overload
    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PipedreamEnvironment = PipedreamEnvironment.PROD,
        project_id: str,
        project_environment: typing.Optional[ProjectEnvironment] = os.getenv("PIPEDREAM_PROJECT_ENVIRONMENT"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        client_id: typing.Optional[str] = os.getenv("PIPEDREAM_CLIENT_ID"),
        client_secret: typing.Optional[str] = os.getenv("PIPEDREAM_CLIENT_SECRET"),
    ): ...
    @typing.overload
    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PipedreamEnvironment = PipedreamEnvironment.PROD,
        project_id: str,
        project_environment: typing.Optional[ProjectEnvironment] = os.getenv("PIPEDREAM_PROJECT_ENVIRONMENT"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        token: typing.Callable[[], str],
    ): ...
    def __init__(self, **kwargs: typing.Any):
        super().__init__(**kwargs)
