# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.connect_usage_response import ConnectUsageResponse
from .raw_client import AsyncRawUsageClient, RawUsageClient


class UsageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUsageClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUsageClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUsageClient
        """
        return self._raw_client

    def list(
        self, *, start_ts: int, end_ts: int, request_options: typing.Optional[RequestOptions] = None
    ) -> ConnectUsageResponse:
        """
        Retrieve Connect usage records for a time window

        Parameters
        ----------
        start_ts : int
            Usage window start timestamp (seconds)

        end_ts : int
            Usage window end timestamp (seconds)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectUsageResponse
            usage records listed

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.usage.list(
            start_ts=1,
            end_ts=1,
        )
        """
        _response = self._raw_client.list(start_ts=start_ts, end_ts=end_ts, request_options=request_options)
        return _response.data


class AsyncUsageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUsageClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUsageClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUsageClient
        """
        return self._raw_client

    async def list(
        self, *, start_ts: int, end_ts: int, request_options: typing.Optional[RequestOptions] = None
    ) -> ConnectUsageResponse:
        """
        Retrieve Connect usage records for a time window

        Parameters
        ----------
        start_ts : int
            Usage window start timestamp (seconds)

        end_ts : int
            Usage window end timestamp (seconds)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectUsageResponse
            usage records listed

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
            project_environment="YOUR_PROJECT_ENVIRONMENT",
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.usage.list(
                start_ts=1,
                end_ts=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(start_ts=start_ts, end_ts=end_ts, request_options=request_options)
        return _response.data
