# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.get_webhook_response import GetWebhookResponse
from ..types.get_webhook_with_signing_key_response import GetWebhookWithSigningKeyResponse
from ..types.set_webhook_response import SetWebhookResponse
from .raw_client import AsyncRawProjectEnvironmentClient, RawProjectEnvironmentClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProjectEnvironmentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProjectEnvironmentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProjectEnvironmentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProjectEnvironmentClient
        """
        return self._raw_client

    def retrieve_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetWebhookResponse:
        """
        Retrieve the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookResponse
            webhook retrieved

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
        )
        client.project_environment.retrieve_webhook()
        """
        _response = self._raw_client.retrieve_webhook(request_options=request_options)
        return _response.data

    def update_webhook(
        self, *, url: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SetWebhookResponse:
        """
        Create or update the webhook URL for a project environment. Creating a webhook returns `signing_key`; updating an existing webhook does not.

        Parameters
        ----------
        url : str
            The webhook URL to set

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetWebhookResponse
            webhook updated

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
        )
        client.project_environment.update_webhook(
            url="url",
        )
        """
        _response = self._raw_client.update_webhook(url=url, request_options=request_options)
        return _response.data

    def delete_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
        )
        client.project_environment.delete_webhook()
        """
        _response = self._raw_client.delete_webhook(request_options=request_options)
        return _response.data

    def regenerate_webhook_signing_key(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhookWithSigningKeyResponse:
        """
        Regenerate the signing key for the project environment webhook

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookWithSigningKeyResponse
            signing key regenerated

        Examples
        --------
        from pipedream import Pipedream

        client = Pipedream(
            project_id="YOUR_PROJECT_ID",
        )
        client.project_environment.regenerate_webhook_signing_key()
        """
        _response = self._raw_client.regenerate_webhook_signing_key(request_options=request_options)
        return _response.data


class AsyncProjectEnvironmentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProjectEnvironmentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProjectEnvironmentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProjectEnvironmentClient
        """
        return self._raw_client

    async def retrieve_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetWebhookResponse:
        """
        Retrieve the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookResponse
            webhook retrieved

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
        )


        async def main() -> None:
            await client.project_environment.retrieve_webhook()


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_webhook(request_options=request_options)
        return _response.data

    async def update_webhook(
        self, *, url: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SetWebhookResponse:
        """
        Create or update the webhook URL for a project environment. Creating a webhook returns `signing_key`; updating an existing webhook does not.

        Parameters
        ----------
        url : str
            The webhook URL to set

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetWebhookResponse
            webhook updated

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
        )


        async def main() -> None:
            await client.project_environment.update_webhook(
                url="url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_webhook(url=url, request_options=request_options)
        return _response.data

    async def delete_webhook(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove the webhook configured for a project environment

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
        )


        async def main() -> None:
            await client.project_environment.delete_webhook()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_webhook(request_options=request_options)
        return _response.data

    async def regenerate_webhook_signing_key(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhookWithSigningKeyResponse:
        """
        Regenerate the signing key for the project environment webhook

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookWithSigningKeyResponse
            signing key regenerated

        Examples
        --------
        import asyncio

        from pipedream import AsyncPipedream

        client = AsyncPipedream(
            project_id="YOUR_PROJECT_ID",
        )


        async def main() -> None:
            await client.project_environment.regenerate_webhook_signing_key()


        asyncio.run(main())
        """
        _response = await self._raw_client.regenerate_webhook_signing_key(request_options=request_options)
        return _response.data
